#!/bin/bash
#
#
# $1: event temp_data folder
# $2: config file
# $3: path to exec finder_run

set -x  
CONF=${2}_PS
FINDERFILE=$3
#FINDERFILE=$SEISCOMP_ROOT"/share/FinDer/finder_file/finder_run"

sed 's/GMT_PLOT .*/GMT_PLOT yes/' $2 > $CONF
sed -i 's/DATA_FOLDER .*/DATA_FOLDER tmp_finder_gif/' $CONF
which pscoast && sed -i 's/GMT_PREFIX .*/GMT_PREFIX --- /' $CONF || ( which gmt && sed -i 's/GMT_PREFIX .*/GMT_PREFIX gmt /' $CONF || (echo GMT not found && exit 1) )

ls -d $1 | while read EVENT;
do
	GIF=${EVENT}/replay.gif
	OUT=${EVENT}/replay.stdout
	ERR=${EVENT}/replay.stderr
	NDATA=$(ls ${EVENT}/data*|wc -l)
	
	ls tmp_finder_gif/temp/ || mkdir -p tmp_finder_gif/temp
	ls tmp_finder_gif/temp/* && rm tmp_finder_gif/temp/*

	$FINDERFILE $CONF ${EVENT} 0 ${NDATA} live > ${OUT} 2> ${ERR}

	ls -ltr tmp_finder_gif/temp/*ps| awk '{print $NF}' |while read F
	do 
		convert -density 100  $F ${F}.jpg 
	done 
	convert -verbose -delay 50 -loop 0 -density 100 $( ls -ltr tmp_finder_gif/temp/*jpg| awk '{print $NF}' ) ${GIF}
done
