#!/bin/bash

D=`date "+%H:%M"`
C=`date "+%H:%M" --date="1 minute ago"`


IFS=$'\n' 
SLINK=($( slinktool -Q $1 |awk '$NF~/'$D'/||$NF~/'$C'/{print $0}'|sed 's;    ; __ ;' ))
echo "${SLINK[*]}"

STAT=($( echo "${SLINK[*]}" |awk '{print $1,$2}'|uniq ))
echo "${STAT[*]}"

echo "${STAT[*]}" | while IFS=" " read N S 
do
	echo $N"."$S":"
	CHAN=($( echo "${SLINK[*]}" |grep "^$N $S"|awk '{print $1,$2,$3,$4}'|uniq ))
	echo "${CHAN[*]}" 
	for O in Z E N 
	do 
		for TRIG in HH$O EH$O SH$O HG$O HN$O EN$O SN$O BH$O LH$O
		do
			echo "${CHAN[*]}" | awk '$NF~/'$TRIG'/{print $0}'
		done
	done|head -1 | while IFS=" " read N S L C
	do 
		echo $N $S $L $C is the best available
		BOND=$SEISCOMP_ROOT/etc/key/station_${N}_${S}
		if [ ! -f $BOND ]
        then
            echo WARNING $N $S no binding reference $BOND 
            break
        fi
        grep global $BOND 
        if [ ! $? -eq 0 ]
        then
            echo WARNING $N $S no global binding in $BOND
            break
        fi
		PROF=`grep global $BOND |sed 's;:;/profile_;'`
		PROFILE=$SEISCOMP_ROOT/etc/key/$PROF
		if [ ! -f $PROFILE ]
        then
            echo WARNING $N $S no profile $PROFILE
            break
        fi
        DETECL=`grep detecLocid $PROFILE `
		echo $DETECL |grep ${L/__/\"\"} || echo WARNING $N $S detecLocid != ${L/__/\"\"}  "("${DETECL} in $PROFILE $BOND")"
		
        DETECC=`grep detecStream $PROFILE ` 
		echo $DETECC |grep ${C:0:2} || echo WARNING $N $S $L detecStream != ${C:0:2} "("${DETECC} in $PROFILE $BOND")"
	done
done
